### ISSUE TITLE
Crash on Windows 10 in dependent project

### ISSUE THREAD

**Issue by chfast** [weidai11/cryptopp#361] opened 2017-01-10 22:15 UTC
I packaged lates master branch for cpp-ethereum project and received this crash report: https://github.com/ethereum/cpp-ethereum/issues/3490. I would more than happy is someone can take a look on the stack trace.

**Comment by noloader** [comment] 2017-01-11 06:01
@chfast, can you provide a recipe for me to duplicate the issue?

**Comment by noloader** [comment] 2017-01-11 08:14
@chfast,

I just tested Master from a Visual Studio x64 Developer Command Prompt (part of VC++ 2015 Build Tools). Everything was OK. The `cl.exe` version is:

```
c:\cryptopp>cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

Its not clear to me what the problem is at the moment. I think we need more information from the Ethereal folks.

However, I will hazard a comment: the access violation at address `0x00000010` could indicate a C++ object was *not* constructed, but a method was called on the class as if it was constructed. If so, that's a symptom of [Static Initialization Order Fiasco](https://www.cryptopp.com/wiki/Static_Initialization_Order_Fiasco). To diagnose it further, we need more information.

-----

Here's what it looks like from the command line. Prior to using `msbuild`, I opened a Git Bash Here and ran `sed` to upgrade the project from VS2010 to VS2015: ` sed -i 's|>v100<|>v140<|g' *.vcxproj`.

```

c:\cryptopp>msbuild cryptlib.vcxproj && msbuild cryptest.vcxproj
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/11/2017 3:10:06 AM.
Project "c:\cryptopp\cryptlib.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "X64\cryptlib\Debug\".
  Creating directory "X64\Output\Debug\".
  Creating directory "X64\cryptlib\Debug\cryptlib.tlog\".
InitializeBuildStatus:
  Creating "X64\cryptlib\Debug\cryptlib.tlog\unsuccessfulbuild" because "AlwaysCreate" was spe
  cified.
CustomBuild:
  Performing Custom Build Tools
  Building and assembling rdrand.asm
   Assembling: c:\cryptopp\rdrand.asm
  Building and assembling x64dll.asm
   Assembling: c:\cryptopp\x64dll.asm
  Building and Assembling x64masm.asm
   Assembling: c:\cryptopp\x64masm.asm
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /Zi /nologo /W4 /
  WX- /Od /Oi /D USE_PRECOMPILED_HEADERS /Gm- /EHsc /RTC1 /MTd /GS /arch:SSE2 /fp:precise /Zc:
  wchar_t /Zc:forScope /Zc:inline /Yc"pch.h" /Fp"X64\cryptlib\Debug\cryptlib.pch" /Fo"X64\cryp
  tlib\Debug\\" /Fd"X64\cryptlib\Debug\cryptlib.pdb" /Gd /TP /errorReport:none pch.cpp
cl : Command line warning D9002: ignoring unknown option '/arch:SSE2' [c:\cryptopp\cryptlib.vc
xproj]
  pch.cpp
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /Zi /nologo /W4 /
  WX- /Od /Oi /D USE_PRECOMPILED_HEADERS /Gm- /EHsc /RTC1 /MTd /GS /arch:SSE2 /fp:precise /Zc:
  wchar_t /Zc:forScope /Zc:inline /Yu"pch.h" /Fp"X64\cryptlib\Debug\cryptlib.pch" /Fo"X64\cryp
  tlib\Debug\\" /Fd"X64\cryptlib\Debug\cryptlib.pdb" /Gd /TP /errorReport:none cryptlib.cpp cp
  u.cpp integer.cpp 3way.cpp adler32.cpp algebra.cpp algparam.cpp arc4.cpp asn.cpp authenc.cpp
   base32.cpp base64.cpp basecode.cpp bfinit.cpp blake2.cpp blowfish.cpp blumshub.cpp camellia
  .cpp cast.cpp casts.cpp cbcmac.cpp ccm.cpp chacha.cpp channels.cpp cmac.cpp crc.cpp default.
  cpp des.cpp dessp.cpp dh.cpp dh2.cpp dsa.cpp eax.cpp ec2n.cpp ecp.cpp elgamal.cpp emsa2.cpp
  esign.cpp files.cpp filters.cpp fips140.cpp fipstest.cpp gcm.cpp gf256.cpp gf2_32.cpp gf2n.c
  pp gfpcrypt.cpp gost.cpp gzip.cpp hex.cpp hmac.cpp hrtimer.cpp ida.cpp idea.cpp keccak.cpp l
  uc.cpp mars.cpp marss.cpp md2.cpp md4.cpp md5.cpp misc.cpp modes.cpp mqueue.cpp mqv.cpp nbth
  eory.cpp network.cpp oaep.cpp osrng.cpp panama.cpp pkcspad.cpp poly1305.cpp polynomi.cpp pss
  r.cpp pubkey.cpp queue.cpp rabin.cpp randpool.cpp rc2.cpp rc5.cpp rc6.cpp rdrand.cpp rdtable
  s.cpp rijndael.cpp ripemd.cpp rng.cpp rsa.cpp rw.cpp safer.cpp salsa.cpp seal.cpp seed.cpp s
  erpent.cpp sha.cpp sha3.cpp shacal2.cpp shark.cpp sharkbox.cpp simple.cpp skipjack.cpp socke
  tft.cpp sosemanuk.cpp square.cpp squaretb.cpp strciphr.cpp tea.cpp tftables.cpp tiger.cpp ti
  gertab.cpp trdlocal.cpp ttmac.cpp twofish.cpp vmac.cpp wait.cpp wake.cpp whrlpool.cpp winpip
  es.cpp xtr.cpp xtrcrypt.cpp zdeflate.cpp zinflate.cpp zlib.cpp
cl : Command line warning D9002: ignoring unknown option '/arch:SSE2' [c:\cryptopp\cryptlib.vc
xproj]
  cryptlib.cpp
  cpu.cpp
  integer.cpp
  3way.cpp
  adler32.cpp
  algebra.cpp
  algparam.cpp
  arc4.cpp
  asn.cpp
  authenc.cpp
  base32.cpp
  base64.cpp
  basecode.cpp
  bfinit.cpp
  blake2.cpp
  blowfish.cpp
  blumshub.cpp
  camellia.cpp
  cast.cpp
  casts.cpp
  Generating Code...
  Compiling...
  cbcmac.cpp
  ccm.cpp
  chacha.cpp
  channels.cpp
  cmac.cpp
  crc.cpp
  default.cpp
  des.cpp
  dessp.cpp
  dh.cpp
  dh2.cpp
  dsa.cpp
  eax.cpp
  ec2n.cpp
  ecp.cpp
  elgamal.cpp
  emsa2.cpp
  esign.cpp
  files.cpp
  filters.cpp
  Generating Code...
  Compiling...
  fips140.cpp
  fipstest.cpp
  gcm.cpp
  gf256.cpp
  gf2_32.cpp
  gf2n.cpp
  gfpcrypt.cpp
  gost.cpp
  gzip.cpp
  hex.cpp
  hmac.cpp
  hrtimer.cpp
  ida.cpp
  idea.cpp
  keccak.cpp
  luc.cpp
  mars.cpp
  marss.cpp
  md2.cpp
  md4.cpp
  Generating Code...
  Compiling...
  md5.cpp
  misc.cpp
  modes.cpp
  mqueue.cpp
  mqv.cpp
  nbtheory.cpp
  network.cpp
  oaep.cpp
  osrng.cpp
  panama.cpp
  pkcspad.cpp
  poly1305.cpp
  polynomi.cpp
  pssr.cpp
  pubkey.cpp
  queue.cpp
  rabin.cpp
  randpool.cpp
  rc2.cpp
  rc5.cpp
  Generating Code...
  Compiling...
  rc6.cpp
  rdrand.cpp
  rdtables.cpp
  rijndael.cpp
  ripemd.cpp
  rng.cpp
  rsa.cpp
  rw.cpp
  safer.cpp
  salsa.cpp
  seal.cpp
  seed.cpp
  serpent.cpp
  sha.cpp
  sha3.cpp
  shacal2.cpp
  shark.cpp
  sharkbox.cpp
  simple.cpp
  skipjack.cpp
  Generating Code...
  Compiling...
  socketft.cpp
  sosemanuk.cpp
  square.cpp
  squaretb.cpp
  strciphr.cpp
  tea.cpp
  tftables.cpp
  tiger.cpp
  tigertab.cpp
  trdlocal.cpp
  ttmac.cpp
  twofish.cpp
  vmac.cpp
  wait.cpp
  wake.cpp
  whrlpool.cpp
  winpipes.cpp
  xtr.cpp
  xtrcrypt.cpp
  zdeflate.cpp
  Generating Code...
  Compiling...
  zinflate.cpp
  zlib.cpp
  Generating Code...
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /Zi /nologo /W4 /
  WX- /Od /Oi /D USE_PRECOMPILED_HEADERS /Gm- /EHsc /RTC1 /MTd /GS /arch:SSE2 /fp:precise /Zc:
  wchar_t /Zc:forScope /Zc:inline /Fo"X64\cryptlib\Debug\\" /Fd"X64\cryptlib\Debug\cryptlib.pd
  b" /Gd /TP /errorReport:none dll.cpp iterhash.cpp
cl : Command line warning D9002: ignoring unknown option '/arch:SSE2' [c:\cryptopp\cryptlib.vc
xproj]
  dll.cpp
  iterhash.cpp
  Generating Code...
Lib:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\Lib.exe /OUT:"X64\Output\De
  bug\cryptlib.lib" /NOLOGO /MACHINE:X64 "X64\cryptlib\Debug\\rdrand-x64.obj"
  X64\cryptlib\Debug\x64dll.obj
  X64\cryptlib\Debug\x64masm.obj
  X64\cryptlib\Debug\cryptlib.obj
  X64\cryptlib\Debug\cpu.obj
  X64\cryptlib\Debug\integer.obj
  X64\cryptlib\Debug\3way.obj
  X64\cryptlib\Debug\adler32.obj
  X64\cryptlib\Debug\algebra.obj
  X64\cryptlib\Debug\algparam.obj
  X64\cryptlib\Debug\arc4.obj
  X64\cryptlib\Debug\asn.obj
  X64\cryptlib\Debug\authenc.obj
  X64\cryptlib\Debug\base32.obj
  X64\cryptlib\Debug\base64.obj
  X64\cryptlib\Debug\basecode.obj
  X64\cryptlib\Debug\bfinit.obj
  X64\cryptlib\Debug\blake2.obj
  X64\cryptlib\Debug\blowfish.obj
  X64\cryptlib\Debug\blumshub.obj
  X64\cryptlib\Debug\camellia.obj
  X64\cryptlib\Debug\cast.obj
  X64\cryptlib\Debug\casts.obj
  X64\cryptlib\Debug\cbcmac.obj
  X64\cryptlib\Debug\ccm.obj
  X64\cryptlib\Debug\chacha.obj
  X64\cryptlib\Debug\channels.obj
  X64\cryptlib\Debug\cmac.obj
  X64\cryptlib\Debug\crc.obj
  X64\cryptlib\Debug\default.obj
  X64\cryptlib\Debug\des.obj
  X64\cryptlib\Debug\dessp.obj
  X64\cryptlib\Debug\dh.obj
  X64\cryptlib\Debug\dh2.obj
  X64\cryptlib\Debug\dll.obj
  X64\cryptlib\Debug\dsa.obj
  X64\cryptlib\Debug\eax.obj
  X64\cryptlib\Debug\ec2n.obj
  X64\cryptlib\Debug\ecp.obj
  X64\cryptlib\Debug\elgamal.obj
  X64\cryptlib\Debug\emsa2.obj
  X64\cryptlib\Debug\esign.obj
  X64\cryptlib\Debug\files.obj
  X64\cryptlib\Debug\filters.obj
  X64\cryptlib\Debug\fips140.obj
  X64\cryptlib\Debug\fipstest.obj
  X64\cryptlib\Debug\gcm.obj
  X64\cryptlib\Debug\gf256.obj
  X64\cryptlib\Debug\gf2_32.obj
  X64\cryptlib\Debug\gf2n.obj
  X64\cryptlib\Debug\gfpcrypt.obj
  X64\cryptlib\Debug\gost.obj
  X64\cryptlib\Debug\gzip.obj
  X64\cryptlib\Debug\hex.obj
  X64\cryptlib\Debug\hmac.obj
  X64\cryptlib\Debug\hrtimer.obj
  X64\cryptlib\Debug\ida.obj
  X64\cryptlib\Debug\idea.obj
  X64\cryptlib\Debug\iterhash.obj
  X64\cryptlib\Debug\keccak.obj
  X64\cryptlib\Debug\luc.obj
  X64\cryptlib\Debug\mars.obj
  X64\cryptlib\Debug\marss.obj
  X64\cryptlib\Debug\md2.obj
  X64\cryptlib\Debug\md4.obj
  X64\cryptlib\Debug\md5.obj
  X64\cryptlib\Debug\misc.obj
  X64\cryptlib\Debug\modes.obj
  X64\cryptlib\Debug\mqueue.obj
  X64\cryptlib\Debug\mqv.obj
  X64\cryptlib\Debug\nbtheory.obj
  X64\cryptlib\Debug\network.obj
  X64\cryptlib\Debug\oaep.obj
  X64\cryptlib\Debug\osrng.obj
  X64\cryptlib\Debug\panama.obj
  X64\cryptlib\Debug\pch.obj
  X64\cryptlib\Debug\pkcspad.obj
  X64\cryptlib\Debug\poly1305.obj
  X64\cryptlib\Debug\polynomi.obj
  X64\cryptlib\Debug\pssr.obj
  X64\cryptlib\Debug\pubkey.obj
  X64\cryptlib\Debug\queue.obj
  X64\cryptlib\Debug\rabin.obj
  X64\cryptlib\Debug\randpool.obj
  X64\cryptlib\Debug\rc2.obj
  X64\cryptlib\Debug\rc5.obj
  X64\cryptlib\Debug\rc6.obj
  X64\cryptlib\Debug\rdrand.obj
  X64\cryptlib\Debug\rdtables.obj
  X64\cryptlib\Debug\rijndael.obj
  X64\cryptlib\Debug\ripemd.obj
  X64\cryptlib\Debug\rng.obj
  X64\cryptlib\Debug\rsa.obj
  X64\cryptlib\Debug\rw.obj
  X64\cryptlib\Debug\safer.obj
  X64\cryptlib\Debug\salsa.obj
  X64\cryptlib\Debug\seal.obj
  X64\cryptlib\Debug\seed.obj
  X64\cryptlib\Debug\serpent.obj
  X64\cryptlib\Debug\sha.obj
  X64\cryptlib\Debug\sha3.obj
  X64\cryptlib\Debug\shacal2.obj
  X64\cryptlib\Debug\shark.obj
  X64\cryptlib\Debug\sharkbox.obj
  X64\cryptlib\Debug\simple.obj
  X64\cryptlib\Debug\skipjack.obj
  X64\cryptlib\Debug\socketft.obj
  X64\cryptlib\Debug\sosemanuk.obj
  X64\cryptlib\Debug\square.obj
  X64\cryptlib\Debug\squaretb.obj
  X64\cryptlib\Debug\strciphr.obj
  X64\cryptlib\Debug\tea.obj
  X64\cryptlib\Debug\tftables.obj
  X64\cryptlib\Debug\tiger.obj
  X64\cryptlib\Debug\tigertab.obj
  X64\cryptlib\Debug\trdlocal.obj
  X64\cryptlib\Debug\ttmac.obj
  X64\cryptlib\Debug\twofish.obj
  X64\cryptlib\Debug\vmac.obj
  X64\cryptlib\Debug\wait.obj
  X64\cryptlib\Debug\wake.obj
  X64\cryptlib\Debug\whrlpool.obj
  X64\cryptlib\Debug\winpipes.obj
  X64\cryptlib\Debug\xtr.obj
  X64\cryptlib\Debug\xtrcrypt.obj
  X64\cryptlib\Debug\zdeflate.obj
  X64\cryptlib\Debug\zinflate.obj
  X64\cryptlib\Debug\zlib.obj
strciphr.obj : warning LNK4221: This object file does not define any previously undefined publ
ic symbols, so it will not be used by any link operation that consumes this library [c:\crypto
pp\cryptlib.vcxproj]
simple.obj : warning LNK4221: This object file does not define any previously undefined public
 symbols, so it will not be used by any link operation that consumes this library [c:\cryptopp
\cryptlib.vcxproj]
polynomi.obj : warning LNK4221: This object file does not define any previously undefined publ
ic symbols, so it will not be used by any link operation that consumes this library [c:\crypto
pp\cryptlib.vcxproj]
algebra.obj : warning LNK4221: This object file does not define any previously undefined publi
c symbols, so it will not be used by any link operation that consumes this library [c:\cryptop
p\cryptlib.vcxproj]
  cryptlib.vcxproj -> c:\cryptopp\X64\Output\Debug\cryptlib.lib
CopyFilesToOutputDirectory:
  Copying file from "X64\cryptlib\Debug\cryptlib.pdb" to "X64\Output\Debug\cryptlib.pdb".
FinalizeBuildStatus:
  Deleting file "X64\cryptlib\Debug\cryptlib.tlog\unsuccessfulbuild".
  Touching "X64\cryptlib\Debug\cryptlib.tlog\cryptlib.lastbuildstate".
Done Building Project "c:\cryptopp\cryptlib.vcxproj" (default targets).


Build succeeded.

"c:\cryptopp\cryptlib.vcxproj" (default target) (1) ->
(ClCompile target) ->
  cl : Command line warning D9002: ignoring unknown option '/arch:SSE2' [c:\cryptopp\cryptlib.
vcxproj]
  cl : Command line warning D9002: ignoring unknown option '/arch:SSE2' [c:\cryptopp\cryptlib.
vcxproj]
  cl : Command line warning D9002: ignoring unknown option '/arch:SSE2' [c:\cryptopp\cryptlib.
vcxproj]


"c:\cryptopp\cryptlib.vcxproj" (default target) (1) ->
(Lib target) ->
  strciphr.obj : warning LNK4221: This object file does not define any previously undefined pu
blic symbols, so it will not be used by any link operation that consumes this library [c:\cryp
topp\cryptlib.vcxproj]
  simple.obj : warning LNK4221: This object file does not define any previously undefined publ
ic symbols, so it will not be used by any link operation that consumes this library [c:\crypto
pp\cryptlib.vcxproj]
  polynomi.obj : warning LNK4221: This object file does not define any previously undefined pu
blic symbols, so it will not be used by any link operation that consumes this library [c:\cryp
topp\cryptlib.vcxproj]
  algebra.obj : warning LNK4221: This object file does not define any previously undefined pub
lic symbols, so it will not be used by any link operation that consumes this library [c:\crypt
opp\cryptlib.vcxproj]

    7 Warning(s)
    0 Error(s)

Time Elapsed 00:01:14.39
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 1/11/2017 3:11:21 AM.
Project "c:\cryptopp\cryptest.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "X64\cryptest\Debug\".
  Creating directory "X64\cryptest\Debug\cryptest.tlog\".
InitializeBuildStatus:
  Creating "X64\cryptest\Debug\cryptest.tlog\unsuccessfulbuild" because "AlwaysCreate" was spe
  cified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /Zi /nologo /W4 /
  WX- /Od /Oi /Gm- /EHsc /RTC1 /MTd /GS /arch:SSE2 /fp:precise /Zc:wchar_t /Zc:forScope /Zc:in
  line /Fo"X64\cryptest\Debug\\" /Fd"X64\cryptest\Debug\vc140.pdb" /Gd /TP /errorReport:none a
  dhoc.cpp bench1.cpp bench2.cpp datatest.cpp dlltest.cpp fipsalgt.cpp regtest.cpp test.cpp va
  lidat0.cpp validat1.cpp validat2.cpp validat3.cpp
cl : Command line warning D9002: ignoring unknown option '/arch:SSE2' [c:\cryptopp\cryptest.vc
xproj]
  adhoc.cpp
  bench1.cpp
  bench2.cpp
  datatest.cpp
  dlltest.cpp
  fipsalgt.cpp
  regtest.cpp
  test.cpp
  validat0.cpp
  validat1.cpp
  validat2.cpp
  validat3.cpp
  Generating Code...
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\link.exe /ERRORREPORT:QUEUE
   /OUT:"X64\Output\Debug\\cryptest.exe" /NOLOGO /LIBPATH:X64\Output\Debug cryptlib.lib Ws2_32
  .lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB
  :"X64\Output\Debug\\cryptlib.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB
  :"X64\Output\Debug\cryptest.lib" /MACHINE:X64 X64\cryptest\Debug\adhoc.obj
  X64\cryptest\Debug\bench1.obj
  X64\cryptest\Debug\bench2.obj
  X64\cryptest\Debug\datatest.obj
  X64\cryptest\Debug\dlltest.obj
  X64\cryptest\Debug\fipsalgt.obj
  X64\cryptest\Debug\regtest.obj
  X64\cryptest\Debug\test.obj
  X64\cryptest\Debug\validat0.obj
  X64\cryptest\Debug\validat1.obj
  X64\cryptest\Debug\validat2.obj
  X64\cryptest\Debug\validat3.obj
  cryptest.vcxproj -> c:\cryptopp\X64\Output\Debug\cryptest.exe
  cryptest.vcxproj -> X64\Output\Debug\\cryptlib.pdb (Full PDB)
FinalizeBuildStatus:
  Deleting file "X64\cryptest\Debug\cryptest.tlog\unsuccessfulbuild".
  Touching "X64\cryptest\Debug\cryptest.tlog\cryptest.lastbuildstate".
Done Building Project "c:\cryptopp\cryptest.vcxproj" (default targets).

Build succeeded.

"c:\cryptopp\cryptest.vcxproj" (default target) (1) ->
(ClCompile target) ->
  cl : Command line warning D9002: ignoring unknown option '/arch:SSE2' [c:\cryptopp\cryptest.
vcxproj]

    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:40.28
```

**Comment by chfast** [comment] 2017-01-11 15:16
Thanks for checking this. We "fixed" this by removing the code that used dynamic initialization and depended on Crypto++. Static initalization order fiasco seems very likely here. Do you have global variables in Crypto++?

**Comment by noloader** [comment] 2017-01-11 15:46
Yes, there are three of them: [Static Initialization Order Fiasco | Static Objects](https://www.cryptopp.com/wiki/Static_Initialization_Order_Fiasco#Static_Objects). However, we take steps to remediate the issue on platforms that offer something. For example, we use an `init_priority` on Linux with GCC.

**Comment by chfast** [comment] 2017-01-11 15:58
The issue was in Crypto++ internally, but in initializing a global variable in cpp-ethereum and in cryptopp lib. It is now fixed, so no acction from you is required.

I just wander, why using helper functions with `static` variables is not an option?

**Comment by noloader** [comment] 2017-01-11 16:14
> I just wonder, why using helper functions with static variables is not an option?

In most places we do. There's a few places we cannot because we would break the ABI by moving symbols around.

Out of curiosity, can you provide the makefile created with Cmake? Email it to *noloader, gmail account*.

**Comment by noloader** [comment] 2017-01-11 22:34
@chfast, Is there anything else we can do here? Can we close the issue?

**Closed** 2017-01-11 22:50 UTC
