### ISSUE TITLE
Including dll.h on Linux raises an error

### ISSUE THREAD

**Issue by guneemwelloeux** [weidai11/cryptopp#524] opened 2017-10-30 10:10 UTC
_Issue_
Compilation of a cpp file including the dll.h header results in an error, due to the #error directive.

_Expected result_
Including dll.h should not result in a compilation error on linux, only on Windows

_Explanation_
dll.h is only relevant to Windows systems (and possibly only the windows compiler cl.exe). Therefore, it should only prevent compilation on Windows systems, and not on Linux

Proposed solution
The #error directive (and all applicable parts of the file) should be protected by a check on a Windows specific preproc macro ( for example #ifdef _MSC_VER).

**Comment by noloader** [comment] 2017-10-30 19:27
What is the platform? How are you building the library?

**Comment by guneemwelloeux** [comment] 2017-10-31 10:08
Hello
I am building the code on Linux, 64 bits processor.
I am using make to build the code.

**Comment by noloader** [comment] 2017-10-31 11:02
Please state the operation system.  Please show the complete build log.

**Comment by guneemwelloeux** [comment] 2017-10-31 12:31
uname -a
Linux hostname 2.6.32.23-0.3-default #1 SMP 2010-10-07 14:57:45 +0200 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 1

gcc (GCC) 7.2.1 20171022

Compilation line:
`gcc -fdump-translation-unit -fkeep-inline-functions -c -x c++-header -fpermissive -w  -std=gnu++17 "dump1.h"  -I/tmp/mwp/osp/Cryptopp/18-0-0-0/include`

Error:
```
In file included from dump1.h:49:0:
/tmp/mwp/osp/Cryptopp/18-0-0-0/include/cryptopp/dll.h:12:2: error: #error To use the DLL version of Crypto++, this file must be included before any other Crypto++ header files.
 #error To use the DLL version of Crypto++, this file must be included before any other Crypto++ header files.

  ^~~~~
```
[dump1.h.txt](https://github.com/weidai11/cryptopp/files/1430676/dump1.h.txt)

**Comment by noloader** [comment] 2017-10-31 12:43
`gcc -c -x c++-header` is unusual. I've never seen it used like that before. What is the purpose of compiling like that? I ask because I need to determine if we need to add a test case to our testing scripts.

`-std=gnu++17` is OK. We regularly test with `-std=gnu++03` and `-std=c++03` through `-std=gnu++17` and `-std=c++17` (including 11 and 14).

Please cat the contents of `dump1.h`.

**Comment by guneemwelloeux** [comment] 2017-10-31 13:07
I attached the file dump1.h.txt to my previous post, which has the same content as dump1.h

The purpose here is to dump the translation unit that gcc uses internally. In turn, we use the results from this step to find out if some symbols have disappeared or changed name (non binary compatible changes)

Since I am re-packaging cryptopp for other users in my company, I need to make sure that any new version I integrate is binary compatible with the previous one.

**Comment by noloader** [comment] 2017-10-31 13:55
You should probably remove the test headers from the list since they don't affect ABI compatibility. Or I don't believe they make a material difference to ABI compat. The test headers are listed below, and anything they provide should be in the `CryptoPP::Test` namespace.

* bench.h
* validate.h
* factory.h

You cannot remove `pch.h` even though its used for Windows precompiled headers. It is inert under Unix and Linux.

You can verify removal of the test headers with:

```
rm bench.h validate.h factory.h
make static dynamic -j 10
```

Regarding `dll.h`, you should probably remove it from the list, too. Below is a list of this uses of `dll.h` (sans it surfacing in a comment):

$ grep 'dll.h' *.h *.cpp
...
dll.cpp:#include "dll.h"
dlltest.cpp:#include "dll.h"
fipsalgt.cpp:#include "dll.h"
fipstest.cpp:#include "dll.h"
test.cpp:#include "dll.h"

The first hit, `dll.cpp`, is used in the library proper (`libcryptopp.a` or `libcryptopp.so`). The remaining hits are the test suite (`cryptest.exe`).

`dll.cpp` cannot be removed from the library. It provides template instantiations used on both Unix and Windows.

Regarding *"... to dump the translation unit that gcc uses internally..."*, I'm not sure how accurate a reproduction it is. But I'm not sure I'm even qualified to say that because I don't have a full understanding of your requirements, or how GCC, the compiler options and the monolithic translation unit achieve the goals.

I think your best bet at this point is to define `CRYPTOPP_DEFAULT_NO_DLL`. It is used in the test suite to avoid the problems `dll.h` causes. Or use `sed` to remove the offending lines:

```
sed -e '10,15d' dll.h > dll.h.fixed
mv dll.h.fixed dll.h
```

**Comment by noloader** [comment] 2017-10-31 15:06
And to be clear about things... I am not sure which of the 3three methods above produces the best results when attempting to determine ABI compatibility from a monolithic translation unit. The three methods are:

* remove `dll.h` header file
* define `CRYPTOPP_DEFAULT_NO_DLL`
* delete the preprocessor block

**Comment by noloader** [comment] 2017-11-02 12:08
@guneemwelloeux,

Is there anything else that needs to be discussed here?

**Comment by noloader** [comment] 2017-11-04 04:05
Closing.

**Closed by noloader** 2017-11-04 04:05 UTC
Labels: ABI/API
