### ISSUE TITLE
use cmake to create dll in widows no support

### ISSUE THREAD

**Issue by owen200008** [weidai11/cryptopp#433] opened 2017-05-29 12:46 UTC
it no export define in cmake.
so it no lib file create.

**Comment by noloader** [comment] 2017-05-29 14:22
The DLL you see in the [Visual Studio solution and project files](https://www.cryptopp.com/wiki/Visual_Studio) is a [FIPS DLL](https://www.cryptopp.com/wiki/FIPS_DLL). Its not very useful to most developers, and its difficult to use for those who [used to] need it.

Users cannot build the FIPS DLL and claim a FIPS validation. The process is, Crypto++ builds the FIPS DLL from the Visual Studio sources, and then submits the binary for validation.

Crypto++ was moved to the Historical Validation list, so the FIPS DLL was marginalized even more.

I suppose you can add the appropriate defines to produce a nearly equivalent DLL  (but without the validated cryptography), but I'm not sure how useful it will be. If you want to see the defines used in the Visual Studio project, then make a quick run with [MSBuild from the Command Line](https://www.cryptopp.com/wiki/MSBuild_(Command_Line)). ***`cryptopp`*** project builds the DLL (it shows the export defines), and ***`dlltest`*** project builds the DLL test harness (it shows the import defines).

**Comment by owen200008** [comment] 2017-05-29 15:42
i think it is useful to add code.
config.h

#ifdef cryptopp_shared_EXPORTS
#define CRYPTOPP_EXPORTS
#endif

**Comment by noloader** [comment] 2017-05-29 22:47
> i think it is useful to add code....

If Cmake is defining `cryptopp_shared_EXPORTS`, then why does it not define `CRYPTOPP_EXPORTS` too?

But stepping back to 10,000 feet, what's the point of trying to build the FIPS DLL with Cmake? You can't use it for its intended purpose, and its hard to use correctly.

**Comment by noloader** [comment] 2017-05-31 00:18
Closing as duplicate of [Issue 358](https://github.com/weidai11/cryptopp/issues/358).

**Closed by noloader** 2017-05-31 00:18 UTC
Labels: cmake

**Comment by noloader** [comment] 2017-09-16 22:39
Last call for CMake patches before removing it from the library and adding it to the patch page. If you have something to add, then now is the time to do it.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) and [Commit 1c740b0a097aecaa](https://github.com/weidai11/cryptopp/commit/1c740b0a097aecaa66044036c0d2c54220eda5d5).
