### ISSUE TITLE
test btea

### ISSUE THREAD

**Issue by ruijiexie** [weidai11/cryptopp#728] opened 2018-10-29 12:48 UTC
`#define MX ((z>>5^y<<2)+(y>>3^z<<4))^((sum^y)+(m_k[(p&3)^e]^z))`
->
`#define MX (((z>>5^y<<2)+(y>>3^z<<4))^((sum^y)+(m_k[(p&3)^e]^z)))`

```
BTEA::Dec::ProcessAndXorBlock(...)
while (sum != 0)
```
->

```
do {} while (sum != 0);
// my machine BIG_ENDIAN_ORDER -> LITTLE_ENDIAN_ORDER
```

```
void test_tea_decrypt()
{
	unsigned char in[] = { 0x55, 0x75, 0xd0, 0x3b, 0x53, 0x82, 0x10, 0x7a };
	unsigned char key[] = { 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66 };
	unsigned char out[] = { 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37 };

	BTEA::Decryption decryption;
	AlgorithmParameters params = MakeParameters("BlockSize", (int)sizeof(in));
	decryption.UncheckedSetKey(key, 16, params);
	decryption.ProcessAndXorBlock(in, NULLPTR, out);
}
```

**Comment by noloader** [comment] 2018-10-29 12:57
I don't follow what you are reporting. It looks like you added an extra parenthesis pair:

    (<-New  ((z>>5^y<<2)+(y>>3^z<<4))^((sum^y)+(m_k[(p&3)^e]^z))  New->)

What is the problem you are reporting?

**Comment by ruijiexie** [comment] 2018-10-29 14:50
> I don't follow what you are reporting. It looks like you added an extra parenthesis pair:
> 
> ```
> (<-New  ((z>>5^y<<2)+(y>>3^z<<4))^((sum^y)+(m_k[(p&3)^e]^z))  New->)
> ```
> What is the problem you are reporting?

yes

**Comment by ruijiexie** [comment] 2018-10-29 15:08
sorry，It is also right for you to write like this. BIG_ENDIAN_ORDER -> LITTLE_ENDIAN_ORDER ，I got the right answer

**Comment by noloader** [comment] 2018-12-06 07:09
@ruijiexie,

Sorry about the late reply here. I tested BTEA on both little and big endian systems and I get the same result. First, the test program:

```
byte k[BTEA::DEFAULT_KEYLENGTH];
byte v[60*4];

std::memset(k, 0, sizeof(k));
std::memset(v, 0, sizeof(v));

byte p[60*4];
byte c[60*4];
byte r[60*4];

std::memset(p, 0, sizeof(p));
std::memset(c, 0, sizeof(c));
std::memset(r, 0, sizeof(r));

p[0] = 1; p[1] = 2; p[2] = 3; p[3] = 4;

ECB_Mode<BTEA>::Encryption enc;
enc.SetKey(k, sizeof(k));
enc.ProcessString(c, p, sizeof(p));

ECB_Mode<BTEA>::Decryption dec;
dec.SetKey(k, sizeof(k));
dec.ProcessString(r, c, sizeof(c));

std::cout << "Plain text:\n";
StringSource(p, sizeof(p), true, new HexEncoder(new FileSink(std::cout)));
std::cout << std::endl;

std::cout << "Cipher text:\n";
StringSource(c, sizeof(c), true, new HexEncoder(new FileSink(std::cout)));
std::cout << std::endl;

std::cout << "Recovered text:\n";
StringSource(r, sizeof(r), true, new HexEncoder(new FileSink(std::cout)));
std::cout << std::endl;
```

Second, the result on both machines:

```
$ ./cryptest.exe
Plain text:
01020304000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
Cipher text:
2359D8EEE4D6C73FF21504B55F946250B6A869629A472459EB49FAAF48F8C40DFDAFEA2032AE066F
64C979A2F62E0436017234253920F9DF8DB8E6731A1DDA52A737F279A10785CC70695E39E2EC1CD2
6608BAE6CAD8145EB67264957026189084AC2E7F046010C620C34A873156900D90C3DFB0364A80E3
27705EDD3652FB4678DBACC066096422CCA5249713F675677BCF6CC8EEBEEAA9F4C11F09E3B02F46
B86410560E2C9CE11663ADACCEC91AF3248788CB61CD9754BBD7011A1016D3B3C8058922D8BA28E5
524503294DE36059EA4EE598421F75EF1757DFE6A7C4232913500952FBCA3C5F32D69CBE63489043
Recovered text:
01020304000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000
```

Things look good to me.

I'm going to close this issue out until I can get a reproducer.

**Closed by noloader** 2018-12-06 07:09 UTC
