### ISSUE TITLE
wiki service down

### ISSUE THREAD

**Issue by miximtor** [weidai11/cryptopp#720] opened 2018-10-13 13:20 UTC
wiki service down

**Comment by noloader** [comment] 2018-10-13 20:30
Thanks @miximtor,

Wiki is up again.

The issue is, the VM is running out of memory. The OOM killer whacks MySQL service which takes down the wiki. Additional details include the service is a GoDaddy VM with 1 GB of RAM and no swap file. We can't purchase more RAM and we can't configure a swap file.

The memory pressures don't occur immediately. They happen over time, but I don't know what triggers it or how much time that is.

We have tried tuning Apache, PHP and the caches but it apparently did not help.

I think I am going to add a cron job that just restarts the MySQL service every four hours.

**Comment by noloader** [comment] 2018-10-13 21:18
Here's the script I added. If anyone has some feedback then please provide it.

```
# cat /etc/cron.hourly/1restart-mysql.sh
#!/usr/bin/env bash

SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin

RUNNING=$(systemctl status mariadb.service | grep -i -c "running")
if [[ "$RUNNING" -eq 0 ]]; then
    systemctl restart mariadb.service
    mysqlcheck --all-databases --auto-repair --user=XXX --password=YYY
fi
```

**Comment by noloader** [comment] 2018-10-17 05:09
We are still seeing the OOM kils, but we are now recovering. I'm going to close this ticket out.

```
$ ssh cryptopp.com
Last login: Sun Oct 14 18:55:40 2018 from 151.196.22.177
cryptopp.com:~$ dmesg
[51136019.298166] Out of memory in UB 5299: OOM killed process 646 (mysqld) score 0 vm:1676040kB, rss:93044kB, swap:0kB
[51136020.928059] Out of memory in UB 5299: OOM killed process 6655 (httpd) score 0 vm:484804kB, rss:28684kB, swap:0kB
[51169283.699444] Out of memory in UB 5299: OOM killed process 14158 (mysqld) score 0 vm:1687172kB, rss:98924kB, swap:0kB
[51176589.945237] Out of memory in UB 5299: OOM killed process 11103 (mysqld) score 0 vm:1690428kB, rss:92472kB, swap:0kB
[51211833.357667] Out of memory in UB 5299: OOM killed process 12726 (mysqld) score 0 vm:1688948kB, rss:93684kB, swap:0kB
[51257914.957573] Out of memory in UB 5299: OOM killed process 20455 (mysqld) score 0 vm:1691024kB, rss:100724kB, swap:0kB
[51268568.528427] Out of memory in UB 5299: OOM killed process 6555 (mysqld) score 0 vm:1684804kB, rss:92412kB, swap:0kB
[51272037.910338] Out of memory in UB 5299: OOM killed process 10087 (mysqld) score 0 vm:1689244kB, rss:92572kB, swap:0kB
[51272039.420328] Out of memory in UB 5299: OOM killed process 9711 (httpd) score 0 vm:484816kB, rss:29308kB, swap:0kB
[51272039.563228] Out of memory in UB 5299: OOM killed process 10603 (httpd) score 0 vm:482560kB, rss:25968kB, swap:0kB
[51272039.695024] Out of memory in UB 5299: OOM killed process 10705 (httpd) score 0 vm:482744kB, rss:25952kB, swap:0kB
[51360994.535889] Out of memory in UB 5299: OOM killed process 11506 (mysqld) score 0 vm:1690432kB, rss:102488kB, swap:0kB
[51383522.229464] Out of memory in UB 5299: OOM killed process 7262 (mysqld) score 0 vm:1682732kB, rss:93120kB, swap:0kB
```

**Closed by noloader** 2018-10-17 05:09 UTC

**Comment by noloader** [comment] 2018-10-20 09:17
[Commit c315c669b73c, Disable server-side Doxygen search](https://github.com/weidai11/cryptopp/commit/c315c669b73c) seems to have resolved the issue. I have not seen any OOM kills since disabling it in the Doxygen config file.

Server-side search never worked anyway.
