### ISSUE TITLE
rad studio xe10

### ISSUE THREAD

**Issue by phy0292** [weidai11/cryptopp#498] opened 2017-09-14 18:57 UTC
Project works in "rad studio xe10" can not be compiled

**Comment by noloader** [comment] 2017-09-14 20:11
Thanks @phy0292,

Yeah, Borland and Embarcadero are not well supported.

I tried to get a license to perform release testing from Embarcadero for about a year. My emails and calls to the company went unanswered. I finally gave up.

If you have some patches you can offer, then please do so.

**Comment by phy0292** [comment] 2017-09-15 06:45
Thanks, @noloader,
Your project is very good, I try to read and understand your code frame structure, but the difficulty is not small. But she is very easy to use.
Ok, I'm trying to submit some bug reports for Embarcadero. Because i can not modify so that compilation can pass.

**Comment by noloader** [comment] 2017-09-15 07:09
> Your project is very good,

Yeah, Crypto++ is a great project. A fellow named Wei Dai wrote it in the early 1990s. Wei is busy with other things now and he does not have a lot of time to spend on the project. His role now is an advisor when we have questions.

> Ok, I'm trying to submit some bug reports for Embarcadero.

OK, thanks.

> Because i can not modify so that compilation can pass.

If you post the compile errors you are seeing then we might be able to help.

**Comment by phy0292** [comment] 2017-09-15 07:53
bds10 in rad studio xe10 is unable to load and upgrade. So I built a new lib project, the need to add the files into the project, set the compiler type is non-clang, and then began to compile.
[bcc32 Error] cpu.cpp (131): E2211 Inline assembly not allowed in inline and template functions
      Remove inline and then compile ...

[bcc32 Error] cpu.cpp (150): E2451 Undefined symbol 'input'
     Delete this line, and then compile ...

......
[bcc32 Error] seckey.h(44): E2313 Constant expression required

[bcc32 Error] mdc.h(19): E2029 'FixedBlockSize<&DIGESTSIZE>' must be a previously defined class or struct

[bcc32 Error] seckey.h(272): E2313 Constant expression required
  Full parser context

[bcc32 Error] mdc.h(19): E2029 'FixedKeyLength<&BLOCKSIZE,4,0>' must be a previously defined class or struct

[bcc32 Error] mdc.h(29): E2029 'MDC_Info<SHA1>' must be a previously defined class or struct

[bcc32 Error] seckey.h(403): E2029 'TwoBases<BlockCipher,MDC_Info<SHA1> >' must be a previously defined class or struct

-------------------------------------------------------------------------------------

If I set the compiler type to clang, I have the following error:
[bcc32c Error] blake2.cpp(49): 'alignas' must be specified on definition if it is specified on any declaration
  blake2.cpp(44): declared with 'alignas' attribute here

[bcc32c Error] blake2.cpp(55): 'alignas' must be specified on definition if it is specified on any declaration
  blake2.cpp(44): declared with 'alignas' attribute here

**Comment by noloader** [comment] 2017-09-15 17:01
@phy0292,

I believe the fixes for `blake2.cpp` and `cpu.cpp` were checked in.

I'm not sure about `seckey.h`, however. The following may work. Would you mind trying it and reporting back with results.

```
$ git diff config.h
diff --git a/config.h b/config.h
index 56526eb..0b34712 100644
--- a/config.h
+++ b/config.h
@@ -657,7 +657,7 @@ NAMESPACE_END
 #endif

 // How to declare class constants
-#if defined(CRYPTOPP_DOXYGEN_PROCESSING)
+#if defined(CRYPTOPP_DOXYGEN_PROCESSING) || defined(__BORLAND__)
 # define CRYPTOPP_CONSTANT(x) static const int x;
 #else
 # define CRYPTOPP_CONSTANT(x) enum {x};
```

It might break something else related to Borland and Embarcadero. That's one of the risks when we don't have the proper test environment for a platform.

**Comment by noloader** [comment] 2017-09-15 18:09
@phy0292,

Speaking of Borland and Embarcadero we have a bunch of features we have not been able to enable due to lack of testing. See the block in [`config.h " 875`](https://github.com/weidai11/cryptopp/blob/master/config.h#L873) or so. For example:

```
// alignof: MS at VS2015 (19.00); GCC at 4.5; Clang at 2.9; Intel 15.0; SunCC 5.13.
#if (CRYPTOPP_MSC_VERSION >= 1900) || __has_feature(cxx_alignof) || \
	(__INTEL_COMPILER >= 1500) || (CRYPTOPP_GCC_VERSION >= 40500) || (__SUNPRO_CC >= 0x5130)
#  define CRYPTOPP_CXX11_ALIGNOF 1
#endif // alignof
```

**Comment by phy0292** [comment] 2017-09-16 03:47
After using the latest update of blake2.cpp and cpu.cpp from yours, then delete cpu.cpp lines 152 and 153 (variable input from where?), And then set the compiler to clang, the compiler is completely normal.
But in the non-clang, there are too many error reports, give up? Or continue?

In addition, the CpiId function in the parameter positioning completely wrong, embarcadero no __cpuid and __cpuidex

In addition, the following is correct
```
// C ++ 11 Features Supported by all:
// http://docwiki.embarcadero.com/RADStudio/Tokyo/en/C%2B%2B11_Features_Supported_by_RAD_Studio_Clang-enhanced_C%2B%2B_Compilers
#if (defined (__ BORLANDC__) & & defined (__ clang__) || defined (_WIN64))
# define CRYPTOPP_CXX11 1
#endif

// c ++ 0x Features Supported by
// http://docwiki.embarcadero.com/RADStudio/XE3/en/C%2B%2B0x_Features_Index
#if (defined (__ BORLANDC__) && __BORLANDC__> = 0x650 / * C ++ Builder XE3 * /
# define CRYPTOPP_CXX11_ALIGNOF 1
#endif
```

**Comment by noloader** [comment] 2017-09-16 04:23
> then delete cpu.cpp lines 152 and 153 (variable input from where?)

`input` was the old parameter name. It was changed to `func`, and `subfunc` was added. If `cpuid` returns `EAX=0` when `func=1`, then the processor is too old so we return failure.

It looks like the function is not exercised well if the typo is being caught now.

-----

> But in the non-clang, there are too many error reports, give up? Or continue?

It is up to you. If you want them fixed, then you need to tell us what they are.

**Comment by phy0292** [comment] 2017-09-16 06:17
```
http://docwiki.embarcadero.com/RADStudio/Tokyo/en/C%2B%2B11_Features_Supported_by_RAD_Studio_Clang-enhanced_C%2B%2B_Compilers
Yes,
#ifdef __clang__ the BCB, must support the C ++ 11 Features, 
#ifndef __clang__ the BCB, from xe3 to the present, only supports c++0x.
& &   It seems that Google translated it after the separation, copy and paste did not check, sorry.
```

**Comment by noloader** [comment] 2017-09-16 14:32
@phy0292,

If Borland/Embarcadero  is defining `__clang__`, then they will be picked up in the LLVM paths. We probably don't need to do anything special.

Is there anything else you will be reporting here? If not, then I will close this report.

**Comment by phy0292** [comment] 2017-09-17 04:55
Please look at the non-clang mode compiler error report, I can not solve. I put the entire compilation information attached to the following,The front is some warning, followed by some errors.:
[1.txt](https://github.com/weidai11/cryptopp/files/1308838/1.txt)

**Comment by noloader** [comment] 2017-09-17 07:16
For the trailing zero issue:

```
  Full parser context
    3way.cpp(5): #include Z:\cryptopp\3way.h
    misc.h(150): namespace CryptoPP
    misc.h(750): decision to instantiate: unsigned int TrailingZeros(unsigned int)
    --- Resetting parser context for instantiation...
    misc.h(728): parsing: unsigned int TrailingZeros(unsigned int)
```

You should either (1) compile with `-mno-bmi`.

Or (2) delete the use of BMI in `misc.h`. Search for all uses of `__BMI__` and delete them, like:

```
 #if defined(__GNUC__) && defined(__BMI__)
 # include <immintrin.h>
 # if defined(__clang__)
 #  ifndef _tzcnt_u32
 #   define _tzcnt_u32(x) __tzcnt_u32(x)
 #  endif
 #  ifndef _blsr_u32
 #    define  _blsr_u32(x)  __blsr_u32(x)
 #  endif
 #  ifdef __x86_64__
 #   ifndef _tzcnt_u64
 #    define _tzcnt_u64(x) __tzcnt_u64(x)
 #   endif
 #   ifndef _blsr_u64
 #     define  _blsr_u64(x)  __blsr_u64(x)
 #   endif
 #  endif  // x86_64
 # endif  // Clang
 #endif  // GNUC and BMI
```

Or (3) contact Borland/Embarcadero and get an updated Clang compiler. If the compiler is going to advertise support for BMI by defining `__BMI__`, then it needs to actually support it.

You should also file a bug report against Borland and Embarcadero for claiming to be GCC by defining `__GNUC__`. If the compiler cannot consume the same program as GCC then it has no business defining `__GNUC__`.

The guards, the defines and the `<immintrin.h>` header are correct. Also see [`_tzcnt_u32`](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_tzcnt_u32) from the Intel Intrinsics guide.

If you have any other things you would like cleared, then please list them.

**Comment by noloader** [comment] 2017-09-17 11:24
I'm not sure what the problem is with the error above. I can't duplicate it on other machines.

Perhaps you can ask one of your coworkers to look at the issue with you. Or maybe your college instructor if you are a student. Or maybe you can find another Borland/Embarcadero user.

If you can't find someone to help with the issue, then open a bug report with Borland/Embarcadero. Ask them to clone the repo to duplicate the problem. Our code is free so they can obtain it. without any troubles. We can't go the other way since we don't have access to their compiler and IDE.

```
// OldRandomPool is provided for backwards compatibility for a migration path
typedef MDC<SHA1> OldRandomPoolCipher;
// Maybe a fix for Borland/Embarcadero and http://github.com/weidai11/cryptopp/issues/498
CRYPTOPP_CONSTANT(OldRandomPoolCipherKeyLength = OldRandomPoolCipher::DEFAULT_KEYLENGTH)

OldRandomPool::OldRandomPool(unsigned int poolSize)
        : pool(poolSize), key(OldRandomPoolCipherKeyLength), addPos(0), getPos(poolSize)
{
	CRYPTOPP_ASSERT(poolSize > key.size());
	::memset(pool, 0, poolSize);
	::memset(key, 0, key.size());
}
```

**Comment by phy0292** [comment] 2017-09-17 17:54
Well, when the compiler is set to clang when the compilation process is completely normal, so there is no problem with the use.
The old compiler will eventually be eliminated later, so we are not backward compatible,
Thank you, wasted you a lot of time.

**Closed** 2017-09-17 18:48 UTC
Labels: borland, enhancement
