### ISSUE TITLE
ECDH Private key length incorrect with secp160r1

### ISSUE THREAD

**Issue by AlanGillespie** [weidai11/cryptopp#785] opened 2019-01-17 16:49 UTC
There appears to be a bug in ECDH with secp160r1 in release 8.0, as illustrated below:

    CryptoPP::ECDH<CryptoPP::ECP>::Domain ecdh((CryptoPP::ASN1::secp160r1());
    cout << ecdh.PrivateKeyLength() << endl;

....prints 21, when I had expected 20. Other curves seem to behave correctly.

I am using VS2017 version 15.9.5 on Windows 10, although I couldn't see any compiler dependencies from the brief look I took at it.

**Comment by noloader** [comment] 2019-01-17 19:00
Thanks @AlanGillespie,

I believe I know why you are seeing this. Early Certicom SEC-1 standards said to use subgroup order rather than field size. For `secp160r1`:

* Subgroup order: `01 00000000 00000000 0001F4C8 F927AED3`
* Field: `FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF 7FFFFFFF`

In fact, here's a comment about it from [`eccrypto.cpp`](https://github.com/weidai11/cryptopp/blob/master/eccrypto.cpp#L746):

```
// SEC 1 ver 1.0 says privateKey (m_d) has the same length as order of the curve
// this will be changed to order of base point in a future version
```

Here is how the `PrivateKeyLength` is retrieved: 

```
unsigned int PrivateKeyLength() const {
    return GetAbstractGroupParameters().GetSubgroupOrder().ByteCount();
}
```
Here is how `AgreedValueLength` is retrieved: 

```
unsigned int AgreedValueLength() const {
    return GetAbstractGroupParameters().GetEncodedElementSize(false);
}
```

What I am less sure about is, what to do next.

**Comment by noloader** [comment] 2019-02-03 10:39
@AlanGillespie,

I had a chance to look at this in more detail. I was hoping to add a define that allows you to specify one version of the standard or the other. The problem is, SEC-2 does not change the way the private key size is calculated.

Here is the text from [SEC-1, v2](http://www.secg.org/sec1-v2.pdf), page 109:

> The component `privateKey` is the private key defined to be the octet string of  `CEIL(log2 n/8)`, (where `n` is the order of the curve) obtained from the unsigned integer via the encoding of Section 2.3.7.

[SEC-2, v2](http://www.secg.org/sec2-v2.pdf) does not revisit it. Searching for `privateKey` returns 0 hits in the document.

Do you have a suggestion on how to handle this for you?

**Comment by noloader** [comment] 2019-02-11 23:12
Closing the issue for now. We may revisit in the future if we can find a path forward.

**Closed by noloader** 2019-02-11 23:12 UTC
Labels: Enhancement
